(function(){
function d(a){if(a!=null)return escape(a.toString());return""}function j(a,c){var e=d(c);if(e!=""){var b=d(a);if(b!="")return"&".concat(b,"=",e)}return""}function m(a){if(a!=null){var c=a.toString();if(2==c.length)return j("hl",c);if(5==c.length)return j("hl",c.substring(0,2))+j("gl",c.substring(3,5))}return""}function n(a,c,e){var b="";if(a){var f=a.screen;if(f){b+=j("u_h",f.height);b+=j("u_w",f.width);b+=j("u_ah",f.availHeight);b+=j("u_aw",f.availWidth);b+=j("u_cd",f.colorDepth)}if(a.history)b+=
j("u_his",a.history.length)}if(e&&typeof e.getTimezoneOffset=="function")b+=j("u_tz",-e.getTimezoneOffset());if(c){if(typeof c.javaEnabled=="function")b+=j("u_java",c.javaEnabled());if(c.plugins)b+=j("u_nplug",c.plugins.length);if(c.mimeTypes)b+=j("u_nmime",c.mimeTypes.length)}return b}function o(a,c){var e="";if(c){var b=c.referrer;if(a&&a.top&&c.location&&a.top.location==c.location){e+=j("ref",b);b=c.location}e+=j("url",b)}return e}function p(a,c,e){var b="";b+=j("gad",a.google_conversion_ad);b+=
j("gkw",a.google_conversion_key);b+=j("gmtc",a.google_conversion_mtc);b+=j("graw",a.google_conversion_raw);b+=j("dom",a.google_conversion_domain);b+=j("cv",a.google_conversion_js_version);b+=j("fst",a.google_conversion_first_time);b+=j("num",a.google_conversion_snippets);b+=j("fmt",a.google_conversion_format);b+=j("value",a.google_conversion_value);b+=j("label",a.google_conversion_label);b+=j("bg",a.google_conversion_color);b+=m(a.google_conversion_language);b+=n(a,c,a.google_conversion_date);b+=
o(a,e);return b}function q(a){if(a&&a.location&&a.location.protocol&&a.location.protocol.toString().toLowerCase()=="https:")return"https:";return"http:"}function r(a,c,e){var b="/?";if(a.google_conversion_type=="landing")b="/extclk?";var f=q(a)+"//www.googleadservices.com/pagead/conversion/"+d(a.google_conversion_id)+b+"random="+d(a.google_conversion_time);f+=p(a,c,e);return f.substring(0,1953)}function s(a){var c={da:1,de:1,en_US:1,en_GB:1,es:1,fi:1,fr:1,it:1,ja:1,ko:1,nl:1,no:1,pt_BR:1,sv:1,zh_CN:1,
zh_TW:1};if(c[a])return a+".html";return"en_US.html"}function t(a,c,e){var b=r(a,c,e),f=function(g,h,i){return'<img height="'+i+'" width="'+h+'" border="0" src="'+g+'" />'};if(a.google_conversion_format==0){var k=q(a)+"//services.google.com/sitestats/"+s(a.google_conversion_language)+"?cid="+d(a.google_conversion_id);return'<a href="'+k+'" target="_blank">'+f(b,135,27)+"</a>"}else return a.google_conversion_snippets>1?f(b,1,1):'<iframe name="google_conversion_frame" width="'+(a.google_conversion_format==
2?200:300)+'" height="'+(a.google_conversion_format==2?26:13)+'" src="'+b+'" frameborder="0" marginwidth="0" marginheight="0" vspace="0" hspace="0" allowtransparency="true" scrolling="no">'+f(b.replace(/\?random=/,"?frame=0&random="),1,1)+"</iframe>"}function u(a){a.google_conversion_date=new Date;a.google_conversion_time=a.google_conversion_date.getTime();if(typeof a.google_conversion_snippets=="number"&&a.google_conversion_snippets>0)a.google_conversion_snippets+=1;else a.google_conversion_snippets=
1;if(typeof a.google_conversion_first_time!="number")a.google_conversion_first_time=a.google_conversion_time;a.google_conversion_js_version="1";if(a.google_conversion_format!=0&&a.google_conversion_format!=1&&a.google_conversion_format!=2)a.google_conversion_format=1}function v(a){a.google_conversion_date=null;a.google_conversion_time=null;a.google_conversion_js_version=null;a.google_conversion_id=null;a.google_conversion_value=null;a.google_conversion_label=null;a.google_conversion_language=null;
a.google_conversion_format=null;a.google_conversion_color=null}function w(a,c){if(a.google_conversion_type=="landing"){function e(g,h){var i,l;if((i=g.indexOf("?"+h+"="))>-1||(i=g.indexOf("?"+h.toUpperCase()+"="))>-1||(i=g.indexOf("&"+h+"="))>-1||(i=g.indexOf("&"+h.toUpperCase()+"="))>-1){l=g.substring(i+h.length+2,g.length);if((i=l.indexOf("&"))>-1)l=l.substring(0,i)}return l}function b(g){if(g){var h=g.match(".?://(www.)?([^/:]+)");if(h&&h.length>=3)return h[2]||""}return""}var f=c.location+"";
a.google_conversion_domain=c.domain?c.domain.toString():"";var k=b(c.referrer);if(k&&(k.indexOf(a.google_conversion_domain)>-1||a.google_conversion_domain.indexOf(k)>-1))f="";a.google_conversion_ad=e(f,"gad");if(a.google_conversion_ad){(a.google_conversion_key=e(f,"gkw"))||(a.google_conversion_key=e(f,"ovkey"));a.google_conversion_mtc=e(f,"ovmtc");a.google_conversion_raw=e(f,"ovraw")}}}function x(a){a.google_conversion_domain=null;a.google_conversion_ad=null;a.google_conversion_key=null;a.google_conversion_mtc=
null;a.google_conversion_raw=null;a.google_conversion_type=null}function y(a,c,e){if(a&&a.google_conversion_id)try{u(a);w(a,e);e.write(t(a,c,e))}finally{v(a);x(a)}}y(window,navigator,document);
})()
