/*       Source:  Local Cache                                                                 */
/*     Location:  rsrc:106001:/html/js/inline_participants.js                                 */
/*      Machine:  10.16.140.108                                                               */
/*    Generated:  July 21st 2008 8:53:34 PM PDT                                               */
/*    HTTP Host:  static.ak.fbcdn.net                                                         */


function InlineParticipants(targetId,asyncUri){this.asyncUri=asyncUri;this.target=$(targetId);this.targetId=targetId;if((!this.target)||this.target.pending){return;}
if(this.target.cached){toggle(this.targetId);}else{this.initializeFromTarget();this.fetchParticipants();}}
copy_properties(InlineParticipants.prototype,{fetchParticipants:function(){this.target.pending=true;new AsyncRequest().setURI(this.asyncUri).setMethod('GET').setReadOnly(true).setData(this.getFetchData()).setHandler(bind(this,'fetchedActorsResponse')).setErrorHandler(bind(this,'fetchedActorsError')).send();this.loadTimeout=setTimeout(this.showLoadIndicator.bind(this),200);},showLoadIndicator:function(){this.loadTimeout=null;if(this.target.pending){this.loading=true;CSS.addClass(this.target,'participants_loading');show(this.target);}},hideLoadIndicator:function(){if(this.loadTimeout){clearTimeout(this.loadTimeout);this.loadTimeout=null;}
if(this.loading){CSS.removeClass(this.target,'participants_loading');}},fetchedActorsResponse:function(asyncResponse){var payload=asyncResponse.getPayload();var show_more=payload["has_more"];var actors=payload["actors"];var nameContainers=[];if(!actors){return this.fetchedActorsError();}
this.hideLoadIndicator();for(var i=0;i<actors.length;i++){var container=this.createNameContainer(actors[i]);this.target.appendChild(container);}
if(show_more){var search_href=this.target.getAttribute("search_href");var search_text=payload['more_text']||this.getSearchText();if(search_href){var search_link=document.createElement("a");search_link.className="see_all";search_link.href=search_href;search_link.appendChild(document.createTextNode(search_text));this.target.appendChild(search_link);}}
this.target.pending=false;this.target.cached=true;animation(this.target).show().from('opacity',0).to('opacity',1).duration(450).go();},getSearchText:function(){return tx('ip:see-all');},fetchedActorsError:function(asyncResponse){this.target.pending=false;var search_href=this.target.getAttribute("search_href");if(search_href){location.href=this.target.search_href;}else{hide(this.target);}},createNameContainer:function(spec){var container=document.createElement("div");container.className="name_container";container.title=spec.name;var pic_link=document.createElement("a");pic_link.className="pic_container";pic_link.href=spec.profile_href;if(spec.profile_onclick){pic_link.setAttribute('onClick',spec.profile_onclick);}
var pic=new Image();pic.alt=spec.name;pic.src=spec.img_src;pic.width='50';pic.height='50';pic_link.appendChild(pic);container.appendChild(pic_link);var name_span=document.createElement("span");name_span.className="name";var name_link=document.createElement("a");name_link.href=spec.profile_href;if(spec.profile_onclick){name_link.setAttribute('onClick',spec.profile_onclick);}
name_link.appendChild(document.createTextNode(spec.first_name));name_span.appendChild(name_link);container.appendChild(name_span);return container;}});function StoryParticipants(targetId,linkData,hash){var asyncUri='/ajax/feed_participants_ajax.php';this.parent.construct(this,targetId,asyncUri);this.linkData=linkData;this.hash=hash;}
copy_properties(StoryParticipants.prototype,{initializeFromTarget:function(){this.storyKey=this.target.getAttribute("story_key");this.storyUser=this.target.getAttribute("user");},getFetchData:function(){if(this.linkData){return{sid:this.storyKey,uid:this.storyUser,link_data:this.linkData,hash:this.hash};}else{return{sid:this.storyKey,uid:this.storyUser};}}});StoryParticipants.extend(InlineParticipants);function MutualFriends(targetId){var asyncUri='/ajax/mutual_friends_ajax.php';this.parent.construct(this,targetId,asyncUri);}
copy_properties(MutualFriends.prototype,{initializeFromTarget:function(){this.friend=this.target.getAttribute("friend");},getFetchData:function(){return{uid:this.friend};},getSearchText:function(){return tx('ip:see-mutuals');}});MutualFriends.extend(InlineParticipants);function SearchMutualFriends(targetId){this.parent.construct(this,targetId);}
copy_properties(SearchMutualFriends.prototype,{getFetchData:function(){return{uid:this.friend,max:8};}});SearchMutualFriends.extend(MutualFriends);
if(window.Bootloader){Bootloader.done(1);}